# Site settings
title: Adventures in Code
email: 
description: "Programming Instructor, code warrior, all around bad ass"
baseurl: ""
url: "http://robawilkinson.github.io/"
twitter_username: RobAWilkinson
github_username:  RobAWilkinson
theme: jekyll-theme-cayman

# Build settings
markdown: redcarpet
permalink: pretty
gems: [redcarpet]
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
