# Site settings
title: Adventures in Code
email: 
description: "Teacher at general Assembly DTLa, code warrior, all around bad ass"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: RobAWilkinson
github_username:  RobAWilkinson

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
